### ISSUE TITLE
git submodule update failed with missing commit message. 

### ISSUE THREAD

**Issue by jiaola** [KnowledgeLinks/dpla-service-hub#1]
Hi, I just tried to follow the setup instruction and got stuck at this step. 

`git submodule update`

And I got this error message: 

error: no such remote ref a7d95210fd089bfa892c5a9ba268e15b2aed1b84
Fetched in submodule path 'bibcat', but it did not contain a7d95210fd089bfa892c5a9ba268e15b2aed1b84. Direct fetching of that commit failed.

It seems there's a commit out of sync? Thanks,

**Comment by jermnelson** [comment]
Hi Jiaola,
I merged the latest changes to the master branches for bibcat and rdfframework and updated the dpla-service-hub repo. If you pull in the latest changes, the correct remotes should be updated correctly when you do a `git submodule update`. 

Let me know if you have any problems.
Thanks,
Jeremy
