### ISSUE TITLE
config.py example

### ISSUE THREAD

**Issue by jiaola** [KnowledgeLinks/dpla-service-hub#2]
In the README (commit: 2da16ff), it mentions a config.py file in the instance directory with two keys in them. Could you please post an example of that file somewhere in the documentation? I am not clear how that file would look like. 

Thanks!

**Comment by jermnelson** [comment]
Hi David,
There is an example config.py file in the example_instance directory (see https://github.com/KnowledgeLinks/dpla-service-hub/tree/master/example_instance).  Just copy the config.py to your newly created instance directory and make any changes to the configuration variables contained in the file.
Thanks,
Jeremy

**Comment by jiaola** [comment]
Thanks Jeremy. That helps! But I run into another issue when I use the config.py file. It seems to expect a rest service at http://localhost:8080/rest. What's the nature of this web service? Is there any way to bypass it? 

Thanks again!

David

**Comment by jiaola** [comment]
@jermnelson  And here is some output - it keeps writing the same message every 10 seconds: 

```
DEBUG:passlib.registry:registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
Ingester import successful
JSON cache directory not found.
Creating directory
Checking status of servers at 0s
	 http://localhost:8080/rest  -  404
	 http://localhost:9999/blazegraph/sparql  - down
Checking status of servers at 10s
	 http://localhost:8080/rest  -  404
	 http://localhost:9999/blazegraph/sparql  - down
Checking status of servers at 20s
	 http://localhost:8080/rest  -  404
	 http://localhost:9999/blazegraph/sparql  - down
```

**Comment by jermnelson** [comment]
Hi @jiaola,
The DPLA Service Hub attempts to connect to two external middleware services, a digital repository Fedora Commons 4.6 running on localhost:8080 and an RDF Triplestore running on localhost:9999/blazegraph/sparql. You can override these values in your instance/config.py file. I'm working on Docker-compose setup for the DPLA Service Hub that will have all of these services running in separate containers similar to what I'm doing for the Colorado Alliance of Research Libraries BIBCAT Project (see https://github.com/KnowledgeLinks/alliance-bibcat). In the meantime, if you have Docker install, you can launch the image I created that bundles both Fedora 4 and Blazegraph in a single container:

`docker run -p 8080:8080 -p 9999:9999 jermnelson/semantic-server-core:dev`

I'll also update the README documentation with this information as well.

Jeremy
